In [1]:
import pandas as pd
import numpy as np
from array import *
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split
df = pd.read_csv('restaurantcustomer.csv')
df.replace('?', np.NaN)

df.dropna()
label_encoder = preprocessing.LabelEncoder() 
X1=df.drop(columns="numberofdaysfininshed",axis=1)
Y1=df[['numberofdaysfininshed']]


In [2]:
X=X1
Y=Y1
X



item  iteminkg  people  children
0     1         3       2         2
1     1         1       2         3
2     2         5       6         2
3     1         1       1         1
4     2         1       4         5

In [3]:
Y

numberofdaysfininshed
0                      3
1                      4
2                      3
3                      1
4                      1

In [5]:
Y.numberofdaysfininshed.unique()

array([3, 4, 1], dtype=int64)

In [6]:
# One-hot encode the data using pandas get_dummies
features = pd.get_dummies(X1)
# Display the first 5 rows of the last 12 columns
features.iloc[:,5:].head(5)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [8]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(Y['numberofdaysfininshed'])
# Remove the labels from the features
# axis 1 refers to the columns
features= X
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [9]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [10]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)


Training Features Shape: (3, 4)
Training Labels Shape: (3,)
Testing Features Shape: (2, 4)
Testing Labels Shape: (2,)


In [11]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [12]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')


Mean Absolute Error: 1.62 degrees.


In [24]:
import pickle

filename = 'rftimeseries.sav'
pickle.dump(rf, open(filename, 'wb'))

In [13]:
errors

array([1.734, 1.498])

In [14]:
test_labels

array([4, 1], dtype=int64)

In [15]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors/ test_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 3.42 %.


In [16]:
len(test_labels)

2

In [17]:
len(predictions)

2

In [18]:
predictions

array([2.266, 2.498])

In [19]:
test_features[[0]]

array([[1, 1, 2, 3]], dtype=int64)

In [22]:
item=1
iteminkg=2
people=1
children=4



predictionsof1 = rf.predict([[item,iteminkg,people,children]])
print(predictionsof1)

[1.98]


In [23]:
predictionsof1

array([1.98])

In [46]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')